apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  storageClassName: ""
  capacity:
    storage: 500Mb
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/xvv1980/pv
  persistentVolumeReclaimPolicy: Delete