apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  storageClassName: ""
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/pv
  persistentVolumeReclaimPolicy: Delete