kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-test
  labels:
    vol: pvc-nfs-test
  namespace: default
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300M