apiVersion: apps/v1
kind: Deployment
metadata:
  name: test04
  labels:
    app: test04-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test04-app
  template:
    metadata:
      labels:
        app: test04-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
     
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
