apiVersion: v1
kind: Service
metadata:
  name: test04-svc-nodeport
spec:
  selector:
    app: test04-app
  ports:
    - protocol: TCP
      nodePort: 30001     
      port: 80
      name: mult-port
    - protocol: TCP
      nodePort: 30002     
      port: 8080
      name: nginx-port
  type: NodePort