apiVersion: v1
kind: Service
metadata:
  name: test04-svc
spec:
  selector:
    app: test04-app
  ports:
    - protocol: TCP
      port: 9001     
      targetPort: 80
      name: mult-port
    - protocol: TCP
      port: 9002     
      targetPort: 8080
      name: nginx-port