apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-init
  labels:
    app: test-init-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-init-app
  template:
    metadata:
      labels:
        app: test-init-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      initContainers:
      - name: init-wait-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup svc-init-test; do echo waiting for myservice; sleep 2; done"]
