apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuber-binding
subjects:
- kind: User
  name: kuber
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kuber-role
  apiGroup: rbac.authorization.k8s.io
