apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-vol
  labels:
    app: test-vol
spec:
  selector:
    matchLabels:
      app: test-vol
  template:
    metadata:
      labels:
        app: test-vol
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
          - mountPath: /test-volume2/syslog
            name: volume
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
      volumes:
      - name: volume
        hostPath: 
           path: /var/log/syslog